ClangSharpPInvokeGenerator `
    -c preview-codegen multi-file generate-vtbl-index-attribute exclude-funcs-with-body `
    -I .\include `
	-f .\include\cor.h `
	    -r _GUID=Guid `
		-r IStream=IntPtr `
		-r tagVARIANT=IntPtr `
		-r ITypeInfo=IntPtr `
	-n CorProf.Bindings `
    -m CorConsts `
	-o .\Cor.Bindings `
	-om CSharp