namespace CorProf.Bindings
{
    public enum COR_PRF_SUSPEND_REASON
    {
        COR_PRF_SUSPEND_OTHER = 0,
        COR_PRF_SUSPEND_FOR_GC = 1,
        COR_PRF_SUSPEND_FOR_APPDOMAIN_SHUTDOWN = 2,
        COR_PRF_SUSPEND_FOR_CODE_PITCHING = 3,
        COR_PRF_SUSPEND_FOR_SHUTDOWN = 4,
        COR_PRF_SUSPEND_FOR_INPROC_DEBUGGER = 6,
        COR_PRF_SUSPEND_FOR_GC_PREP = 7,
        COR_PRF_SUSPEND_FOR_REJIT = 8,
        COR_PRF_SUSPEND_FOR_PROFILER = 9,
    }
}
