namespace CorProf.Bindings
{
    public enum COR_PRF_HIGH_MONITOR
    {
        COR_PRF_HIGH_MONITOR_NONE = 0,
        COR_PRF_HIGH_ADD_ASSEMBLY_REFERENCES = 0x1,
        COR_PRF_HIGH_IN_MEMORY_SYMBOLS_UPDATED = 0x2,
        COR_PRF_HIGH_MONITOR_DYNAMIC_FUNCTION_UNLOADS = 0x4,
        COR_PRF_HIGH_DISABLE_TIERED_COMPILATION = 0x8,
        COR_PRF_HIGH_BASIC_GC = 0x10,
        COR_PRF_HIGH_MONITOR_GC_MOVED_OBJECTS = 0x20,
        COR_PRF_HIGH_REQUIRE_PROFILE_IMAGE = 0,
        COR_PRF_HIGH_MONITOR_LARGEOBJECT_ALLOCATED = 0x40,
        COR_PRF_HIGH_MONITOR_EVENT_PIPE = 0x80,
        COR_PRF_HIGH_MONITOR_PINNEDOBJECT_ALLOCATED = 0x100,
        COR_PRF_HIGH_ALLOWABLE_AFTER_ATTACH = (((((COR_PRF_HIGH_IN_MEMORY_SYMBOLS_UPDATED | COR_PRF_HIGH_MONITOR_DYNAMIC_FUNCTION_UNLOADS) | COR_PRF_HIGH_BASIC_GC) | COR_PRF_HIGH_MONITOR_GC_MOVED_OBJECTS) | COR_PRF_HIGH_MONITOR_LARGEOBJECT_ALLOCATED) | COR_PRF_HIGH_MONITOR_EVENT_PIPE),
        COR_PRF_HIGH_ALLOWABLE_NOTIFICATION_PROFILER = ((((((COR_PRF_HIGH_IN_MEMORY_SYMBOLS_UPDATED | COR_PRF_HIGH_MONITOR_DYNAMIC_FUNCTION_UNLOADS) | COR_PRF_HIGH_DISABLE_TIERED_COMPILATION) | COR_PRF_HIGH_BASIC_GC) | COR_PRF_HIGH_MONITOR_GC_MOVED_OBJECTS) | COR_PRF_HIGH_MONITOR_LARGEOBJECT_ALLOCATED) | COR_PRF_HIGH_MONITOR_EVENT_PIPE),
        COR_PRF_HIGH_MONITOR_IMMUTABLE = COR_PRF_HIGH_DISABLE_TIERED_COMPILATION,
    }
}
