namespace CorProf.Bindings
{
    public enum COR_PRF_EVENTPIPE_PARAM_TYPE
    {
        COR_PRF_EVENTPIPE_OBJECT = 1,
        COR_PRF_EVENTPIPE_BOOLEAN = 3,
        COR_PRF_EVENTPIPE_CHAR = 4,
        COR_PRF_EVENTPIPE_SBYTE = 5,
        COR_PRF_EVENTPIPE_BYTE = 6,
        COR_PRF_EVENTPIPE_INT16 = 7,
        COR_PRF_EVENTPIPE_UINT16 = 8,
        COR_PRF_EVENTPIPE_INT32 = 9,
        COR_PRF_EVENTPIPE_UINT32 = 10,
        COR_PRF_EVENTPIPE_INT64 = 11,
        COR_PRF_EVENTPIPE_UINT64 = 12,
        COR_PRF_EVENTPIPE_SINGLE = 13,
        COR_PRF_EVENTPIPE_DOUBLE = 14,
        COR_PRF_EVENTPIPE_DECIMAL = 15,
        COR_PRF_EVENTPIPE_DATETIME = 16,
        COR_PRF_EVENTPIPE_GUID = 17,
        COR_PRF_EVENTPIPE_STRING = 18,
        COR_PRF_EVENTPIPE_ARRAY = 19,
    }
}
