namespace CorProf.Bindings
{
    public enum COR_PRF_EVENTPIPE_LEVEL
    {
        COR_PRF_EVENTPIPE_LOGALWAYS = 0,
        COR_PRF_EVENTPIPE_CRITICAL = 1,
        COR_PRF_EVENTPIPE_ERROR = 2,
        COR_PRF_EVENTPIPE_WARNING = 3,
        COR_PRF_EVENTPIPE_INFORMATIONAL = 4,
        COR_PRF_EVENTPIPE_VERBOSE = 5,
    }
}
