namespace CorProf.Bindings
{
    public enum CorExceptionFlag
    {
        COR_ILEXCEPTION_CLAUSE_NONE,
        COR_ILEXCEPTION_CLAUSE_OFFSETLEN = 0x0000,
        COR_ILEXCEPTION_CLAUSE_DEPRECATED = 0x0000,
        COR_ILEXCEPTION_CLAUSE_FILTER = 0x0001,
        COR_ILEXCEPTION_CLAUSE_FINALLY = 0x0002,
        COR_ILEXCEPTION_CLAUSE_FAULT = 0x0004,
        COR_ILEXCEPTION_CLAUSE_DUPLICATED = 0x0008,
    }
}
