using static CorProf.Bindings.CorElementType;

namespace CorProf.Bindings
{
    public enum CorSerializationType
    {
        SERIALIZATION_TYPE_UNDEFINED = 0,
        SERIALIZATION_TYPE_BOOLEAN = ELEMENT_TYPE_BOOLEAN,
        SERIALIZATION_TYPE_CHAR = ELEMENT_TYPE_CHAR,
        SERIALIZATION_TYPE_I1 = ELEMENT_TYPE_I1,
        SERIALIZATION_TYPE_U1 = ELEMENT_TYPE_U1,
        SERIALIZATION_TYPE_I2 = ELEMENT_TYPE_I2,
        SERIALIZATION_TYPE_U2 = ELEMENT_TYPE_U2,
        SERIALIZATION_TYPE_I4 = ELEMENT_TYPE_I4,
        SERIALIZATION_TYPE_U4 = ELEMENT_TYPE_U4,
        SERIALIZATION_TYPE_I8 = ELEMENT_TYPE_I8,
        SERIALIZATION_TYPE_U8 = ELEMENT_TYPE_U8,
        SERIALIZATION_TYPE_R4 = ELEMENT_TYPE_R4,
        SERIALIZATION_TYPE_R8 = ELEMENT_TYPE_R8,
        SERIALIZATION_TYPE_STRING = ELEMENT_TYPE_STRING,
        SERIALIZATION_TYPE_SZARRAY = ELEMENT_TYPE_SZARRAY,
        SERIALIZATION_TYPE_TYPE = 0x50,
        SERIALIZATION_TYPE_TAGGED_OBJECT = 0x51,
        SERIALIZATION_TYPE_FIELD = 0x53,
        SERIALIZATION_TYPE_PROPERTY = 0x54,
        SERIALIZATION_TYPE_ENUM = 0x55,
    }
}
